### ISSUE TITLE
[BUGS]: return_collapses 

### ISSUE THREAD

**Issue by zhuyuanxiang** [pyvista/fast-simplification#46]
Environmental:
python=3.8.19, vedo=2024.5.1, vtk=9.3.1, fast-simplication=0.1.7
os=Windows11
mesh's vertices number > 50000, cells number > 100000
Code:

```python
        mesh = vedo.file_io.load(file_name_path.as_posix())
        vertices, cells = mesh.vertices, mesh.cells
        vertices_num, cells_num = len(vertices), len(cells)
        vertices_out, cells_out, collapse_index = fast_simplification.simplify(
            vertices, cells, target_count=20000, agg=3, return_collapses=True
        )
        vertices_out_num = vertices_out.shape[0]
        collapse_len = collapse_index.shape[0]
```

Then, it is a error that `collapse_len <(vertices_num-vertices_out_num)`, because `collapse_len`'s meaning is how many points is collapsed, and `collapse_len` should greater than `(vertices_num-vertices_out_num)`.

Now, I need use this index for collapse the labels, please give me some help! Thanks!

**Comment by akaszynski** [comment]
Pinging @Louis-Pujol

**Comment by zhuyuanxiang** [comment]
Hi, @Louis-Pujol

Thks for your help!

Now, I know the reason about `collapse_len <(vertices_num-vertices_out_num)`, but I need the `isolated_points` in the `_map_isolated_points()` for collapse the labels in the pointdata. I hope how to do it. 

If I could get a new `simplify()` to get the `isolated_points`, or I could use the `replay_simplification()` to simpily the mesh and modify it for return the `isolated_points`?

BTW:  I have not found `isolated_points` in another project scikit-shapes too.

**Comment by Louis-Pujol** [comment]
Hi @zhuyuanxiang,

`replay_simplification()` has been designed to do both operations: concatenations and cleaning of isolated points, and the output consists in three arrays:

- the decimated points
- the decimated triangles
- `indice_mapping` with the following description : ``indice_mapping[i] = j`` means that the vertex ``i`` of the original mesh was mapped to the vertex ``j`` of the decimated mesh.

So if you use `replay_simplification()`, you don't need to care about `isolated_points`, it is just an intermediate step of the global decimation process. And I think `indice_mapping` is the output you will need to collapse the labels, in scikit-shapes, we use it to transfer data (landmarks or signal) from fine meshes to coarse meshes.

**Comment by zhuyuanxiang** [comment]
Hi, @Louis-Pujol :

Thks for your conduct. Now I known what to do and how to do. I will follow your step to implement my algorithm. It's my luck to have your help. Wish you health and happiness.

Yours sincerely friend
ZhuYuanxiang.Tom

**Comment by Louis-Pujol** [comment]
You're welcome ! I wish you all the best too
